name: vegan_liverpool
version: 1.5.0+27
publish_to: none
description: Food, Grocery delivery platform for Vegan products and food, with a built in wallet running on the Fuse network
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  analyzer: ^4.7.0
  another_flushbar: ^1.12.29
  app_tracking_transparency: ^2.0.1
  auto_route: ^5.0.2
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.2.1
  carrier_info: ^2.0.4 #Gets country code from mobile carrier
  charge_wallet_sdk: ^0.0.2
  confetti: ^0.7.0
  country_code_picker: ^2.0.2 #Sign up screen
  decimal: ^2.3.0
  dio: ^4.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  expandable_sliver_list: ^4.1.1
  firebase_analytics: ^9.3.8
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  flex_color_scheme: ^5.1.0
  flutter_dotenv: ^5.0.0
  flutter_form_builder: ^7.7.0
  flutter_inappwebview: ^5.7.1
  flutter_localized_locales: ^2.0.2
  flutter_redux: ^0.10.0
  flutter_secure_storage: ^6.0.0
  flutter_sticky_header: ^0.6.4
  flutter_stripe: ^5.1.0
  flutter_svg: ^1.1.5
  flutter_udid: ^2.0.0
  font_awesome_flutter: ^10.2.1
  form_builder_extra_fields: ^8.3.0
  form_builder_validators: ^8.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_api_headers: ^1.4.0
  html: ^0.15.0
  image_picker: ^0.8.6
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+4
  json_annotation: ^4.3.0
  local_auth: ^2.1.2
  logger: ^1.0.0
  modal_bottom_sheet: ^2.1.2
  nil: ^1.1.1 #TODO: replace SizedBox.shrink with Nil everywhere
  number_display: ^3.0.0
  package_info: ^2.0.2 #Gets application info, used to show application and build version
  phone_number: ^1.0.0
  pin_code_fields: ^7.2.0
  redux_dev_tools: ^0.7.0
  redux_logging: ^0.5.0
  redux_persist: ^0.9.0
  redux_thunk: ^0.4.0
  responsive_framework: ^0.2.0
  sentry_flutter: ^6.12.2
  shimmer: ^2.0.0
  simple_animations: ^5.0.0+2
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.6
  uuid: ^3.0.6
  wallet_connect: ^1.0.4
  ethereum_addresses:
    git:
      url: https://github.com/fuseio/dart-ethereum_address.git
      ref: master
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.2
  build_runner: ^2.1.8
  dependency_validator: ^3.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.1.1
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.3
  very_good_analysis: ^3.0.2
flutter:
  assets:
    - environment/.env
    - environment/.env_qa
    - environment/.env_dev
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Fat Cheeks
      fonts:
        - asset: assets/fonts/FatCheeks-Regular.ttf
    - family: Europa
      fonts:
        - asset: assets/fonts/europa-regular-webfont.ttf
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 300
        - asset: assets/fonts/europa-light-webfont.ttf
          weight: 400
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 600
        - asset: assets/fonts/europa-regular-webfont.ttf
          weight: 700
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 800
        - asset: assets/fonts/europa-bold-webfont.ttf
          weight: 900
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: I10n
  main_locale: en_US
